# Generated by Django 3.2.4 on 2021-06-10 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0002_estudiante_tipo_estudiante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('1', 'Primero'), ('2', 'Segundo')], max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='edad',
            field=models.IntegerField(verbose_name='edad de estudiante'),
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=200)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativo.estudiante')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativo.modulo')),
            ],
        ),
    ]
